// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0RKcp14W3so6TehakihzJzUyV7p6j8jQ',
    appId: '1:144687589221:web:c151753fb5c8151ccc238c',
    messagingSenderId: '144687589221',
    projectId: 'peacefulness-app-2268f',
    authDomain: 'peacefulness-app-2268f.firebaseapp.com',
    storageBucket: 'peacefulness-app-2268f.appspot.com',
    measurementId: 'G-K09L9NHMKN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC55Mn7bYKkaCLyIN6jJjZaeVUbeCBhl4A',
    appId: '1:144687589221:android:cc1a9c8a2ddf2566cc238c',
    messagingSenderId: '144687589221',
    projectId: 'peacefulness-app-2268f',
    storageBucket: 'peacefulness-app-2268f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwDjFARvlI6ptUcRBxOJOEH5zP-fFtZ-Q',
    appId: '1:144687589221:ios:06e2e0b8e00b69facc238c',
    messagingSenderId: '144687589221',
    projectId: 'peacefulness-app-2268f',
    storageBucket: 'peacefulness-app-2268f.appspot.com',
    iosClientId: '144687589221-rlqsm11k4keunio1f5s48muij07m4gs3.apps.googleusercontent.com',
    iosBundleId: 'com.example.peacefulnessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwDjFARvlI6ptUcRBxOJOEH5zP-fFtZ-Q',
    appId: '1:144687589221:ios:7e750b92ec6dc491cc238c',
    messagingSenderId: '144687589221',
    projectId: 'peacefulness-app-2268f',
    storageBucket: 'peacefulness-app-2268f.appspot.com',
    iosClientId: '144687589221-u85d333mg0r51qb06u85nhtl1mv3m230.apps.googleusercontent.com',
    iosBundleId: 'com.example.peacefulnessApp.RunnerTests',
  );
}
